### ISSUE TITLE
[PE-D][Tester B] Minimum height of window is too large

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-T08-3/tp#105]
![image.png](https://raw.githubusercontent.com/bryanyee33/ped/main/files/e93cda04-5d65-404f-9d38-f176d38dccce.png)

When the app is not in full screen, it gets cut off at the end. I am also unable to make the window height any smaller, making it hard to view the details of the contact at the bottom, especially if it is the last contact (cannot scroll down any further).

The location of the save file is also not visible.

This issue is not present in full screen:

![image.png](https://raw.githubusercontent.com/bryanyee33/ped/main/files/bd031d4f-bec5-4b5a-830f-20e72402da2b.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: bryanyee33/ped#3

**Comment by Lalelulilulela** [comment]
App does not get cut off at the end and it can be scrolled all the way to the end even when not in fullscreen
