### ISSUE TITLE
[PE-D][Tester E] User guide add command is not updated

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-T08-3/tp#129]
## Description
The `add` command instructions in the user guide are outdated and do not match the current application release's `MESSAGE_USAGE` format. This documentation issue was identified while referencing the functional bug issue #1.

## Expected Behavior
The user guide should provide the correct format for the `add` command, mirroring the `MESSAGE_USAGE` found in the actual application release. This ensures users are guided correctly on how to add a person.

## Actual Behavior
The current user guide contains an outdated format for the `add` command, which does not correspond with the latest application release's `add` command usage.
![Outdated User Guide Screenshot](https://raw.githubusercontent.com/jmsandiegoo/ped/main/files/ec2461fc-cd9c-44c0-9660-5de1423fdc1e.png)

## Additional Information
The discrepancy between the user guide and the application's current `add` command may lead to user confusion and unsuccessful attempts to add new person records. Referenced screenshots demonstrate the mismatch.

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: jmsandiegoo/ped#5

**Comment by Lalelulilulela** [comment]
Updated UG already
