### ISSUE TITLE
[PE-D][Tester E] Interview time argument `tt/` is unintuitive

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-T08-3/tp#134]
## Description
The `add` and `edit` commands are challenging for end users due to the interview time field `tt/`, which is a required parameter. The current format for inputting time is unintuitive and not user-friendly.

## Expected Behavior
Users should be able to input the interview time using a proper date-time format, preferably in the form of `DD-MM-YYYY HH:mm`, which is a widely recognized standard.

## Actual Behavior
Currently, the command accepts a numeric value representing the interview time for a person's record in the application, which is not intuitive for users to interpret or enter.

![Datetime Numeric Value Example](https://raw.githubusercontent.com/jmsandiegoo/ped/main/files/04262366-aef4-4f21-8c6d-3f824c0adda3.png)
_The picture depicts the datetime numeric value corresponding to December 12, 2022, at 02:00 PM._

## Potential Fix
The application could leverage Java's `LocalDateTime` class to parse and handle the interview time field value, which would allow for a more intuitive date-time input from users.

-------------
Labels: `type.FeatureFlaw` `severity.High`
original: jmsandiegoo/ped#6

**Comment by dabzpengu** [comment]
feature flaw

**Comment by dabzpengu** [comment]
considered design decision
