### ISSUE TITLE
[PE-D][Tester B] No spacing between programming languages

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-T08-3/tp#145]
![image.png](https://raw.githubusercontent.com/bryanyee33/ped/main/files/3cbd630d-44ce-4cb3-8cbb-6a075a8c063b.png)

When multiple programming languages are put per person, there are no spaces or commas between each programming language. Also, repeating "Programming Languages:" seems redundant, and makes it harder to read.

-------------
Labels: `type.FeatureFlaw` `severity.VeryLow`
original: bryanyee33/ped#11

**Comment by dabzpengu** [comment]
feature flaw

**Comment by Lalelulilulela** [comment]
Should be a functionality bug as we expect only one programming language title followed by the programming languages added to be displayed
