### ISSUE TITLE
[PE-D][Tester E] User guide for `find` command is not updated

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-T08-3/tp#146]
## Description
The 'find' command documentation in the user guide is not updated to reflect the actual functionality of the command in the current application release.

## Expected Behavior
The user guide should be updated to reflect that the `find` command can search by both name and company name, in line with the current application's capabilities.

## Actual Behavior
The user guide incorrectly indicates that the `find` command can only search by name, which is different with the `MESSAGE_USAGE` in the application's current release that allows finding by name and company name.

_User guide screenshot_:
![User Guide Screenshot](https://raw.githubusercontent.com/jmsandiegoo/ped/main/files/fa5cacf9-2268-4a80-ac4e-4e812947f6ec.png)

_Current Application Release Message Usage screenshot_:
![Current Application Release Message Usage Screenshot](https://raw.githubusercontent.com/jmsandiegoo/ped/main/files/9dd7e854-1901-476d-8e07-94ee054ca78b.png)

## Additional Information
This discrepancy could lead to confusion among users, potentially resulting in ineffective search attempts or the underutilization of the application's search capabilities.

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: jmsandiegoo/ped#8

**Comment by Lalelulilulela** [comment]
Done
