### ISSUE TITLE
[PE-D][Tester B] No warning when save file is corrupted

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-T08-3/tp#152]
![image.png](https://raw.githubusercontent.com/bryanyee33/ped/main/files/d333dfd4-6732-495c-981e-b2b18e127d60.png)

When the JSON save file is corrupted, there are no indications on the app that something went wrong, or that executing a command would wipe this save file that can potentially be recovered.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: bryanyee33/ped#15

**Comment by dabzpengu** [comment]
feature flaw

**Comment by Dexter-Wong** [comment]
resolved
