### ISSUE TITLE
[PE-D][Tester E] The Application Does Not Allow People with the Same Name

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-T08-3/tp#157]
## Description
The application is intended for computer professionals to manage job applications and contacts of recruiters and interviewers. Given the nature of the usage, it is highly likely to encounter multiple individuals sharing the same name. However, the application currently does not support the addition of multiple people with identical names.

## Steps to Reproduce
1. Add a person with a given name to the application (e.g., `add cn/Google n/John Doe p/98765432 e/johnd@example.com a/311, Clementi Ave 2, #02-25 tt/121220221400 i/Birthday: 12 May 2001 s/5000 pl/Java t/friends `).
2. Attempt to add another person with the same name but different contact details (e.g., `add cn/Meta n/John Doe p/91234567 e/johndifferent@example.com a/300, Jurong Ave 1, #01-20 tt/121220221400 i/Birthday: 11 May 2000 s/5000 pl/Java t/friends `).

## Expected Behavior
The application should allow multiple entries with the same name, differentiating them based on other unique attributes like phone number or email address.

## Actual Behavior
The application prevents the addition of a new person record if another record with the same name already exists.

![image.png](https://raw.githubusercontent.com/jmsandiegoo/ped/main/files/b4a608ef-e68e-4ca8-825c-a9fc7a25685f.png)

## Additional Information
In real-world usage scenarios, particularly in professional settings, it is common to have contacts with the same name, and the application should be able to handle such cases. This limitation could significantly hinder the user's ability to manage job applications and professional contacts effectively.

-------------
Labels: `type.FeatureFlaw` `severity.High`
original: jmsandiegoo/ped#11

**Comment by Lalelulilulela** [comment]
feature flaw
